In [1]:
import sys

sys.path.append('../')

In [2]:
from typing import Text
import pandas as pd

In [3]:
def create_mock_raw_dataframe() -> pd.DataFrame:
    """ Create raw mock dataframe """
    return pd.DataFrame({
        'ID': ['S1']*9 + ['S2']*7 + ['S3']*8 + ['S4']*7,
        'Time Points': [0, 1, 1, 1, 2, 2, 3, 4, 4, 5, 5, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 13, 14, 15, 16, 16, 17, 18, 19],
        'Items': ['a', 'a', 'b', 'c', 'a', 'c', 'd', 'c', 'f', 'a', 'd', 'c', 'b', 'c', 'a', 'e', 'e', 'f', 'a', 'b', 'd', 'f', 'c', 'b', 'e', 'g', 'a', 'f', 'c', 'b', 'c'],
    })

def create_mock_raw_dataframe_nosep() -> pd.DataFrame:
    """ Create raw mock dataframe """
    return pd.DataFrame({
        'ID': ['S1']*16,
        'Time Points': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
        'Items': ['A', 'A', 'G', 'T', 'A', 'C', 'G', 'A', 'C', 'G', 'C', 'A', 'T', 'C', 'T', 'A'],
    })

test_file_path = '../tests/test_files/contextPrefixSpan.txt'

In [4]:
# Raw input - Sequence IDs and Itemsets can have arbitrary labels and time points may be repeated for simultaneous events 
mock_df_raw = create_mock_raw_dataframe()
mock_df_raw

    ID  Time Points Items
0   S1            0     a
1   S1            1     a
2   S1            1     b
3   S1            1     c
4   S1            2     a
5   S1            2     c
6   S1            3     d
7   S1            4     c
8   S1            4     f
9   S2            5     a
10  S2            5     d
11  S2            6     c
12  S2            7     b
13  S2            7     c
14  S2            8     a
15  S2            8     e
16  S3            9     e
17  S3            9     f
18  S3           10     a
19  S3           10     b
20  S3           11     d
21  S3           11     f
22  S3           12     c
23  S3           13     b
24  S4           14     e
25  S4           15     g
26  S4           16     a
27  S4           16     f
28  S4           17     c
29  S4           18     b
30  S4           19     c

In [5]:
# Raw input - for NOSEP
create_mock_raw_dataframe_nosep()

    ID  Time Points Items
0   S1            1     A
1   S1            2     A
2   S1            3     G
3   S1            4     T
4   S1            5     A
5   S1            6     C
6   S1            7     G
7   S1            8     A
8   S1            9     C
9   S1           10     G
10  S1           11     C
11  S1           12     A
12  S1           13     T
13  S1           14     C
14  S1           15     T
15  S1           16     A

### Sequential Pattern Mining Examples

In [6]:
from spmf import PrefixSpan

prefixspan = PrefixSpan(min_support=0.5)
mock_df = create_mock_raw_dataframe()
output = prefixspan.run_pandas(mock_df)
output

   Frequent sequential pattern Support
0                            a       4
1                          a b       2
2                     a b -> c       2
3                     a b -> d       2
4                a b -> d -> c       2
5                     a b -> f       2
6                       a -> a       2
7                       a -> b       4
8                     a -> b c       2
9                a -> b c -> a       2
10                 a -> b -> a       2
11                 a -> b -> c       2
12                      a -> c       4
13                 a -> c -> a       2
14                 a -> c -> b       3
15                 a -> c -> c       3
16                      a -> d       2
17                 a -> d -> c       2
18                      a -> f       2
19                           b       4
20                         b c       2
21                    b c -> a       2
22                      b -> a       2
23                      b -> c       3
24                      b -> d       2
25                 b -> d -> c       2
26                      b -> f       2
27                           c       4
28                      c -> a       2
29                      c -> b       3
30                      c -> c       3
31                           d       3
32                      d -> b       2
33                      d -> c       3
34                 d -> c -> b       2
35                           e       3
36                      e -> a       2
37                 e -> a -> b       2
38                 e -> a -> c       2
39            e -> a -> c -> b       2
40                      e -> b       2
41                 e -> b -> c       2
42                      e -> c       2
43                 e -> c -> b       2
44                      e -> f       2
45                 e -> f -> b       2
46                 e -> f -> c       2
47            e -> f -> c -> b       2
48                           f       3
49                      f -> b       2
50                 f -> b -> c       2
51                      f -> c       2
52                 f -> c -> b       2

In [7]:
from spmf import SPADE

spade = SPADE(min_support=0.5)
mock_df = create_mock_raw_dataframe()
output = spade.run_pandas(mock_df)
output

   Frequent sequential pattern Support
0                            a       4
1                            b       4
2                            c       4
3                            d       3
4                            e       3
5                            f       3
6                       e -> f       2
7                       f -> c       2
8                       b -> f       2
9                       f -> b       2
10                      a -> f       2
11                 f -> c -> b       2
12                 f -> b -> c       2
13                      e -> c       2
14                      e -> b       2
15                      e -> a       2
16                 e -> a -> b       2
17                 e -> a -> c       2
18            e -> a -> c -> b       2
19                 e -> c -> b       2
20                 e -> b -> c       2
21                 e -> f -> b       2
22                 e -> f -> c       2
23            e -> f -> c -> b       2
24                      d -> c       3
25                      b -> d       2
26                      d -> b       2
27                      a -> d       2
28                 d -> c -> b       2
29                      c -> c       3
30                         b c       2
31                      b -> c       3
32                      c -> b       3
33                      a -> c       4
34                      c -> a       2
35                         a b       2
36                      a -> b       4
37                      b -> a       2
38                    b c -> a       2
39                 b -> d -> c       2
40                      a -> a       2
41                 a -> b -> a       2
42                 a -> c -> a       2
43                    a -> b c       2
44                 a -> c -> b       3
45                 a -> b -> c       2
46               a -> b c -> a       2
47                    a b -> c       2
48                    a b -> d       2
49                    a b -> f       2
50               a b -> d -> c       2
51                 a -> c -> c       3
52                 a -> d -> c       2

In [8]:
from spmf import CMSPADE

cmspade = CMSPADE(min_support=0.5)
mock_df = create_mock_raw_dataframe()
output = cmspade.run_pandas(mock_df)
output

   Frequent sequential pattern Support
0                            a       4
1                            b       4
2                            c       4
3                            d       3
4                            e       3
5                            f       3
6                       e -> f       2
7                       f -> c       2
8                       b -> f       2
9                       f -> b       2
10                      a -> f       2
11                 f -> c -> b       2
12                 f -> b -> c       2
13                      e -> c       2
14                      e -> b       2
15                      e -> a       2
16                 e -> a -> b       2
17                 e -> a -> c       2
18            e -> a -> c -> b       2
19                 e -> c -> b       2
20                 e -> b -> c       2
21                 e -> f -> b       2
22                 e -> f -> c       2
23            e -> f -> c -> b       2
24                      d -> c       3
25                      b -> d       2
26                      d -> b       2
27                      a -> d       2
28                 d -> c -> b       2
29                      c -> c       3
30                         b c       2
31                      b -> c       3
32                      c -> b       3
33                      a -> c       4
34                      c -> a       2
35                         a b       2
36                      a -> b       4
37                      b -> a       2
38                    b c -> a       2
39                 b -> d -> c       2
40                      a -> a       2
41                 a -> b -> a       2
42                 a -> c -> a       2
43                    a -> b c       2
44                 a -> c -> b       3
45                 a -> b -> c       2
46               a -> b c -> a       2
47                    a b -> c       2
48                    a b -> d       2
49                    a b -> f       2
50               a b -> d -> c       2
51                 a -> c -> c       3
52                 a -> d -> c       2

In [9]:
from spmf import SPAM

spam = SPAM(min_support=0.5)
mock_df = create_mock_raw_dataframe()
output = spam.run_pandas(mock_df)
output

   Frequent sequential pattern Support
0                            a       4
1                            b       4
2                            c       4
3                            d       3
4                            e       3
5                            f       3
6                       a -> a       2
7                       a -> b       4
8                  a -> b -> a       2
9                  a -> b -> c       2
10                    a -> b c       2
11               a -> b c -> a       2
12                      a -> c       4
13                 a -> c -> a       2
14                 a -> c -> b       3
15                 a -> c -> c       3
16                      a -> d       2
17                 a -> d -> c       2
18                      a -> f       2
19                         a b       2
20                    a b -> c       2
21                    a b -> d       2
22               a b -> d -> c       2
23                    a b -> f       2
24                      b -> a       2
25                      b -> c       3
26                      b -> d       2
27                 b -> d -> c       2
28                      b -> f       2
29                         b c       2
30                    b c -> a       2
31                      c -> a       2
32                      c -> b       3
33                      c -> c       3
34                      d -> b       2
35                      d -> c       3
36                 d -> c -> b       2
37                      e -> a       2
38                 e -> a -> b       2
39                 e -> a -> c       2
40            e -> a -> c -> b       2
41                      e -> b       2
42                 e -> b -> c       2
43                      e -> c       2
44                 e -> c -> b       2
45                      e -> f       2
46                 e -> f -> b       2
47                 e -> f -> c       2
48            e -> f -> c -> b       2
49                      f -> b       2
50                 f -> b -> c       2
51                      f -> c       2
52                 f -> c -> b       2

In [10]:
from spmf import CMClaSP

cmclasp = CMClaSP(min_support=0.5)
mock_df = create_mock_raw_dataframe()
output = cmclasp.run_pandas(mock_df)
output

Before removing NonClosed patterns there are 45 patterns

   Frequent sequential pattern Support
0                a -> b c -> a       2
1                a b -> d -> c       2
2                     a b -> f       2
3                  a -> b -> c       2
4                  d -> c -> b       2
5                       d -> c       3
6                  a -> c -> c       3
7             e -> a -> c -> b       2
8                  e -> b -> c       2
9             e -> f -> c -> b       2
10                 f -> b -> c       2
11                      b -> c       3
12                           f       3
13                 a -> c -> b       3
14                           e       3
15                      a -> b       4
16                      a -> c       4

In [11]:
from spmf.seq_pat import VMSP

vmsp = VMSP(min_support=0.5)
mock_df = create_mock_raw_dataframe()
output = vmsp.run_pandas(mock_df)
output

  Frequent sequential pattern Support
0                 f -> b -> c       2
1                 e -> b -> c       2
2                    a b -> f       2
3                 d -> c -> b       2
4                 a -> c -> c       3
5                 a -> b -> c       2
6            e -> f -> c -> b       2
7            e -> a -> c -> b       2
8               a b -> d -> c       2
9               a -> b c -> a       2

In [12]:
from spmf import VGEN

vgen = VGEN(min_support=0.5)
mock_df = create_mock_raw_dataframe()
output = vgen.run_pandas(mock_df)
output

   Frequent sequential pattern Support
0                                    4
1                            d       3
2                            f       3
3                            e       3
4                       a -> a       2
5                       b -> a       2
6                          b c       2
7                       c -> a       2
8                       a -> d       2
9                       a -> f       2
10                         a b       2
11                      b -> d       2
12                      b -> f       2
13                      d -> b       2
14                      c -> c       3
15                      b -> c       3
16                      e -> f       2
17                      e -> a       2
18                      e -> b       2
19                      e -> c       2
20                      f -> b       2
21                      f -> c       2
22                      c -> b       3
23                 a -> b -> c       2

In [13]:
from spmf import NOSEP

nosep = NOSEP(min_pattern_length=1, max_pattern_length=20, min_gap=0, max_gap=2, min_support=3)
mock_df = create_mock_raw_dataframe_nosep()
output = nosep.run_pandas(mock_df)
output

   Frequent sequential pattern Support
0                            A       6
1                            C       4
2                            G       3
3                            T       3
4                       A -> A       3
5                       A -> C       3
6                       A -> G       3
7                       C -> A       3
8                       C -> C       3
9                       G -> A       3
10                      G -> C       3
11                 A -> A -> G       3
12                 A -> C -> A       3
13                 A -> G -> A       3
14                 A -> G -> C       3
15                 G -> A -> C       3
16                 G -> C -> C       3
17            A -> A -> G -> A       3
18            A -> A -> G -> C       3
19            A -> G -> A -> C       3
20            A -> G -> C -> C       3
21            G -> A -> C -> A       3
22       A -> A -> G -> A -> C       3
23       A -> A -> G -> C -> C       3
24       A -> G -> A -> C -> A       3
25  A -> A -> G -> A -> C -> A       3

In [14]:
from spmf import TKS

tks = TKS(k=5)
mock_df = create_mock_raw_dataframe()
output = tks.run_pandas(mock_df)
output

  Frequent sequential pattern Support
0                           c       4
1                      a -> b       4
2                           b       4
3                      a -> c       4
4                           a       4